### ISSUE TITLE
很多注释/说明缺字

### ISSUE THREAD

**Issue by lsh1994** [makelove/OpenCV-Python-Tutorial#9]
感谢作者分享，很多地方注释/说明缺字影响体验😂，请问有别的说明或指导吗？
![image](https://user-images.githubusercontent.com/14355014/59480609-d6683100-8e93-11e9-81d7-3e438820ce19.png)

**Comment by makelove** [comment]
可以说是笔记，对理解程序比较有用。
有些是翻译过来，复制过来的。

看你喜欢了。
